### ISSUE TITLE
Timezone settings in php

### ISSUE THREAD

**Issue by abcdmitry** [TetraWeb/docker#16]
Add timezone setting like recommended by PHP

**Comment by mkurzeja** [comment]
Here is my quick solution for this issue [my gitlab-ci.yml]:

```
image: tetraweb/php:5.6

before_script:
  - echo "date.timezone = Europe/Warsaw" > /usr/local/etc/php/php.ini
  - docker-php-ext-enable zip
  - composer self-update
  - composer install

php-5.6:
  script:
    - bin/security-checker security:check
```

Of course the only important line is this one:

```
  - echo "date.timezone = Europe/Warsaw" > /usr/local/etc/php/php.ini
```

**Comment by abcdmitry** [comment]
In case container already has user-created php.ini it's better to run
`echo "date.timezone = Europe/Warsaw" > /usr/local/etc/php/conf.d/timezone.ini`

**Comment by abcdmitry** [comment]
You can now set `TIMEZONE` environment variable in config.toml or right in .gitlab-ci.yml
