### ISSUE TITLE
memcache(d) extension

### ISSUE THREAD

**Issue by abcdmitry** [TetraWeb/docker#28]

**Comment by giggsey** [comment]
I added the pecl memcache module to a fork of this yesterday: https://github.com/TetraWeb/docker/compare/master...giggsey:master

(It also has other changes (openssh-client, allowing the 'intl' extension), so I haven't submitted a clean PR). I can do so if you want?

**Comment by abcdmitry** [comment]
I've enabled intl extension. But memcache is supposed to be installed via pecl (like mongo and redis extensions)

**Comment by abcdmitry** [comment]
Just added both `memcache` and `memcached` modules

**Comment by giggsey** [comment]
Can you add memcache(d) to the PHP7 images too?

**Comment by abcdmitry** [comment]
It doesn't seem that memcache(d) is compatible with PHP7 already. At least I can't install it with `pecl install`

**Comment by giggsey** [comment]
Good point. I see https://github.com/php-memcached-dev/php-memcached/tree/php7, but that's memcached

**Comment by abcdmitry** [comment]
I tried both `pecl install memcache` and `pecl install memcached`. Neither does work.
I'd prefer to convince authors of memcached to release php7 compatible version to pecl repository first rather than trying to implement a module from some experimental branch.

**Comment by giggsey** [comment]
I agree, it needs to follow the proper releases.
