### ISSUE TITLE
OpenSSH Client?

### ISSUE THREAD

**Issue by giggsey** [TetraWeb/docker#31]
My composer install fails because it tries to clone from my GitLab. Can openssh-client be part of the main image?

Also, is there a sane way of passing a private key, so it can ssh into my GitLab box. At the moment, I have a script which fetches a private key from my LAN, key scanning the host (to add the key)

**Comment by abcdmitry** [comment]
Good idea, just enabled it.

Run `/etc/cron.weekly/docker-update-images` on your CI box to update the images

The only way recommended by GitLab is to set environment variables in Project settings / Variables. They will be passed to runner environment
