### ISSUE TITLE
no mbstring extension on latest tetraweb/php:5.5 image ?

### ISSUE THREAD

**Issue by changwuf31** [TetraWeb/docker#44]
Is it just me, or some of the extension are missing ?

Thank u

**Comment by abcdmitry** [comment]
It is just not loaded by default.
You're supposed to run `docker-php-ext-enable mbstring` to load it
Check [README](https://github.com/TetraWeb/docker/blob/master/php/README.md#php-modules) for the list of compiled-in extensions and extensions available for loading with `docker-php-ext-enable`
