### ISSUE TITLE
All installed php extensions are missing

### ISSUE THREAD

**Issue by Jekis** [TetraWeb/docker#45]
Why do you remove all extensions?

```
for ext in $phpModules; do \
    rm -f /usr/local/etc/php/conf.d/docker-php-ext-$ext.ini; \
done
```

**Comment by abcdmitry** [comment]
I don't think all extensions should be loaded by default. For example xdebug slows down composer and it is better to enable it after `composer install`.
You can still enable any extension listed on README page with `docker-php-ext-enable`

**Comment by Jekis** [comment]
Yes, you are right. It would be nice to mention this in readme :) Thank you!

**Comment by abcdmitry** [comment]
Here you go https://github.com/TetraWeb/docker/tree/master/php#php-modules

**Comment by Jekis** [comment]
My fault!
