### ISSUE TITLE
PHP 7 XDebug not found?

### ISSUE THREAD

**Issue by giggsey** [TetraWeb/docker#48]
> Using Docker executor with image tetraweb/php:7.0-cli ...
> Pulling docker image tetraweb/php:7.0-cli ...
> 
> $ docker-php-ext-enable xdebug
> error: /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug does not exist
> 
> usage: /usr/local/bin/docker-php-ext-enable module-name [module-name ...]
>    ie: /usr/local/bin/docker-php-ext-enable gd mysqli
>        /usr/local/bin/docker-php-ext-enable pdo pdo_mysql
> 
> Possible values for module-name:
> bcmath.so bz2.so calendar.so dba.so enchant.so exif.so ftp.so gd.so gettext.so gmp.so imap.so intl.so ldap.so mbstring.so mcrypt.so mongodb.so mysqli.so opcache.so pcntl.so pdo.so pdo_dblib.so pdo_mysql.so pdo_pgsql.so pgsql.so pspell.so shmop.so snmp.so soap.so sockets.so sysvmsg.so sysvsem.so sysvshm.so tidy.so wddx.so xmlrpc.so xsl.so zip.so

I've done a `docker pull tetraweb/php:7.0-cli`, and it's still happening with that.

**Comment by abcdmitry** [comment]
Please refer to https://hub.docker.com/r/tetraweb/php/tags/ for the list of available tags. -cli tags were just aliases and were removed few months ago.
