### ISSUE TITLE
PHP 7.1?

### ISSUE THREAD

**Issue by L00Cyph3r** [TetraWeb/docker#51]
I just started with using GitLab CI with these excellent images, but since I want to be prepared for the future, I would like to test with PHP7.1 (RC6 is currently the latest).

Would it be possible to create a 7.1RC6 version, or do you want to wait until it's final?

Many thanks in advance!

**Comment by abcdmitry** [comment]
Yes, I think it's time to include 7.1-rc

**Comment by stayallive** [comment]
Since it's final now, would be awesome to hava a 7.1 available 👍

**Comment by abcdmitry** [comment]
PHP 7.1 pushed to the repository. Will be available from docker hub within an hour or so

**Comment by stayallive** [comment]
Thanks @abcdmitry!
